backend:
  name: git-gateway
  branch: main

media_folder: "img/noticias"
public_folder: "/img/noticias"

collections:
  - name: "noticias"
    label: "Noticias"
    folder: "noticias"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Contenido", name: "body", widget: "markdown" }
      - { label: "Imagen", name: "image", widget: "image" }
