backend:
  name: git-gateway
  branch: main  # o la rama que uses

media_folder: "img/noticias"       # Carpeta donde se guardan las imágenes
public_folder: "/img/noticias"     # Ruta pública para acceder a las imágenes

collections:
  - name: "noticias"
    label: "Noticias"
    folder: "noticias"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "titulo", widget: "string" }
      - { label: "Categoría", name: "categoria", widget: "string" }
      - { label: "Imagen", name: "imagen", widget: "image" }
      - { label: "Link de Facebook", name: "facebook", widget: "string" }
